/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rideurbicycle;

import ListManagement.ListManager;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.*;
import sql.DBAdapter;
import util.Strings;

/**
 *
 * @author flibbo
 */
public class RideUrBicycle extends javax.swing.JFrame {

    /**
     * Creates new form AdditionUI
     */
    private int startX;
    private int startY;
    private int goalX;
    private int goalY;
    private int sizeX, sizeY;

    private int fahrerListIndexOfSelected;
    private int fahrerComboIndexOfSelected;

    private String fahrerNewFName;
    private String fahrerNewLName;

    private DBAdapter dbAdapter;

    private ListManager fahrerListManager;
    private ListManager ordersListManager;

    public RideUrBicycle() {
        initVariables();
        initComponents();
        initLists();
        updateOrderViews();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        firstNum = new javax.swing.JLabel();
        secontNum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        clearBut = new javax.swing.JButton();
        addButt = new javax.swing.JButton();
        exitBut = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        orderStartXBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        orderStartYBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        orderGoalXBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        orderGoalYBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        orderListe = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        editFahrerFNameText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        submitFahrerBut = new javax.swing.JButton();
        submitOrderBut = new javax.swing.JButton();
        editFahrerLNameText = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        fahrerListe = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        chooseFahrerBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        actualOrderLabel = new javax.swing.JLabel();
        orderDoneBut = new javax.swing.JButton();
        retrieveOrder = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Addition"));

        firstNum.setText("FirstNum");

        secontNum.setText("SecondNUm");

        jLabel3.setText("Result");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        clearBut.setText("Clear");
        clearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButActionPerformed(evt);
            }
        });

        addButt.setText("Add");
        addButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNum)
                    .addComponent(secontNum)
                    .addComponent(jLabel3)
                    .addComponent(addButt))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearBut)
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNum)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secontNum)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBut)
                    .addComponent(addButt))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        exitBut.setText("Exit");
        exitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(jLabel1);

        jTabbedPane2.addTab("Courir", jScrollPane2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("I want to ride my bicycle Kurier");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Startadresse:");

        orderStartXBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        orderStartXBox.setToolTipText("X Koordinate der Abholadresse");
        orderStartXBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderStartXBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("X:");

        jLabel5.setText("Y:");

        orderStartYBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        orderStartYBox.setToolTipText("Y Koordinate der Abholadresse");
        orderStartYBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderStartYBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Zieladresse:");

        jLabel7.setText("X:");

        orderGoalXBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        orderGoalXBox.setToolTipText("X Koordinate der Zieladresse");
        orderGoalXBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderGoalXBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Y:");

        orderGoalYBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        orderGoalYBox.setToolTipText("Y Koordinate der Zieladresse");
        orderGoalYBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderGoalYBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Neuen Auftrag anlegen");

        orderListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(orderListe);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Fahrer einfügen/ ändern");

        jLabel14.setText("Vorname:");

        editFahrerFNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFahrerFNameTextActionPerformed(evt);
            }
        });

        jLabel15.setText("Nachname:");

        submitFahrerBut.setText("übernehmen");
        submitFahrerBut.setToolTipText("Eingabe für Vor- und Nachname in Datenbank übernehmen");
        submitFahrerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFahrerButActionPerformed(evt);
            }
        });

        submitOrderBut.setText("Auftrag speichern");
        submitOrderBut.setToolTipText("Auftrag mit den eingegebenen Daten in die Datenbank übernehmen");
        submitOrderBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitOrderButActionPerformed(evt);
            }
        });

        fahrerListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        fahrerListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fahrerListe.setToolTipText("clicken auf Eintrag, um Vor- oder Nachname zu ändern");
        fahrerListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fahrerListeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(fahrerListe);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText(" Anr.  Fahrer   Datum                   Zeit    Start X Y   Ziel X Y             Status");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2))
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(orderStartXBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(orderGoalXBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(orderGoalYBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(orderStartYBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 120, Short.MAX_VALUE)
                                .addComponent(submitOrderBut))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editFahrerFNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editFahrerLNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(submitFahrerBut)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(orderStartXBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(orderStartYBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderGoalYBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(orderGoalXBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(submitOrderBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(editFahrerFNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(editFahrerLNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitFahrerBut))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Manager", jPanel4);

        chooseFahrerBox.setToolTipText("wählen Sie den aktuellen Fahrer aus");
        chooseFahrerBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chooseFahrerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFahrerBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Fahrer wählen");

        jLabel11.setText("aktueller Auftrag:");

        actualOrderLabel.setBackground(new java.awt.Color(153, 255, 153));
        actualOrderLabel.setText("  ");

        orderDoneBut.setText("erledigt");
        orderDoneBut.setToolTipText("Auftrag als erledigt markieren, Fahrer ist wieder verfügbar");
        orderDoneBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDoneButActionPerformed(evt);
            }
        });

        retrieveOrder.setText("neuen Auftrag abrufen");
        retrieveOrder.setToolTipText("hier clicken, um dem Fahrer Auftrag mit der kürzesten Entfernung zum aktuellen Standort zuzuteilen");
        retrieveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveOrderActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("aktueller Auftrag");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(orderDoneBut)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(retrieveOrder))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(341, 341, 341))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(chooseFahrerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)))
                    .addComponent(actualOrderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(chooseFahrerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actualOrderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderDoneBut)
                    .addComponent(retrieveOrder))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Fahrer", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void clearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButActionPerformed

    }//GEN-LAST:event_clearButActionPerformed

    private void exitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButActionPerformed

    }//GEN-LAST:event_exitButActionPerformed

    private void addButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtActionPerformed

    }//GEN-LAST:event_addButtActionPerformed

    private void orderStartXBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderStartXBoxActionPerformed
        startX = (Integer.parseInt(orderStartXBox.getSelectedItem().toString()));
    }//GEN-LAST:event_orderStartXBoxActionPerformed

    private void orderGoalXBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderGoalXBoxActionPerformed
        goalX = (Integer.parseInt(orderGoalXBox.getSelectedItem().toString()));
    }//GEN-LAST:event_orderGoalXBoxActionPerformed

    private void orderDoneButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDoneButActionPerformed
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        dbAdapter.markOrderDone(fahrerComboIndexOfSelected);
        updateOrderViews();
        updateFahrerViews();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_orderDoneButActionPerformed

    private void editFahrerFNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFahrerFNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFahrerFNameTextActionPerformed

    private void orderStartYBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderStartYBoxActionPerformed
        startY = (Integer.parseInt(orderStartYBox.getSelectedItem().toString()));
    }//GEN-LAST:event_orderStartYBoxActionPerformed

    private void orderGoalYBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderGoalYBoxActionPerformed
        goalY = (Integer.parseInt(orderGoalYBox.getSelectedItem().toString()));
    }//GEN-LAST:event_orderGoalYBoxActionPerformed

    private void submitOrderButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitOrderButActionPerformed
        if (startX != -1 && startY != -1 && goalX != -1 && goalY != -1) {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            dbAdapter.createOrder(startX, startY, goalX, goalY);
            updateOrderViews();
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_submitOrderButActionPerformed

    private void submitFahrerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFahrerButActionPerformed
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        fahrerNewFName = editFahrerFNameText.getText();
        fahrerNewLName = editFahrerLNameText.getText();
        dbAdapter.updateFahrer(fahrerNewFName, fahrerNewLName, fahrerListIndexOfSelected);
        updateFahrerViews();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        fahrerListIndexOfSelected = -1;
        fahrerListe.clearSelection();
        editFahrerFNameText.setText("");
        editFahrerLNameText.setText("");

    }//GEN-LAST:event_submitFahrerButActionPerformed

    private void fahrerListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fahrerListeMouseClicked
        fahrerListIndexOfSelected = fahrerListe.getSelectedIndex();
        System.out.println(fahrerListIndexOfSelected);
        String tempVName = dbAdapter.getFahrerVNameAt(fahrerListIndexOfSelected);
        String tempNName = dbAdapter.getFahrerNNameAt(fahrerListIndexOfSelected);
        editFahrerFNameText.setText(tempVName);
        editFahrerLNameText.setText(tempNName);
    }//GEN-LAST:event_fahrerListeMouseClicked

    private void retrieveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveOrderActionPerformed
        fahrerComboIndexOfSelected = chooseFahrerBox.getSelectedIndex();
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        String assignedOrder = dbAdapter.findClosestOrder(fahrerComboIndexOfSelected);
        actualOrderLabel.setText(assignedOrder);
        updateOrderViews();
        retrieveOrder.setEnabled(false);
        if (!assignedOrder.equals(Strings.NO_ORDER_ASSIGNED)) {
            orderDoneBut.setEnabled(true);
        }
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_retrieveOrderActionPerformed

    private void chooseFahrerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFahrerBoxActionPerformed
        fahrerComboIndexOfSelected = chooseFahrerBox.getSelectedIndex();
        if (fahrerComboIndexOfSelected >= 0) {
            actualOrderLabel.setText(dbAdapter.getActualOrderForDriver(fahrerComboIndexOfSelected));
            retrieveOrder.setEnabled(!dbAdapter.alreadyHasJob(fahrerComboIndexOfSelected));
            orderDoneBut.setEnabled(dbAdapter.alreadyHasJob(fahrerComboIndexOfSelected));
        }
    }//GEN-LAST:event_chooseFahrerBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RideUrBicycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RideUrBicycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RideUrBicycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RideUrBicycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RideUrBicycle().setVisible(true);
            }
        });
    }

    private void initVariables() {
        startX = -1;
        startY = -1;
        goalX = -1;
        goalY = -1;

        sizeX = 10;
        sizeY = 10;

        fahrerListIndexOfSelected = -1;

        fahrerNewFName = "";
        fahrerNewLName = "";

        dbAdapter = new DBAdapter(sizeX, sizeY);
    }

    private void updateOrderViews() {
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ordersListManager.updateList(dbAdapter.getAllOrdersAsStringList());
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void updateFahrerViews() {
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ArrayList<String> temp = dbAdapter.getAllFahrerAsStringList();
        fahrerListManager.updateList(temp);
        updateFahrerComboBox(temp);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void updateFahrerComboBox(ArrayList<String> list) {
        chooseFahrerBox.removeAllItems();

        for (int i = 0; i < list.size(); i++) {
            String str = list.get(i);
            chooseFahrerBox.addItem(str);
        }
    }

    private void initLists() {
        DefaultListModel fahrerListModel = new DefaultListModel();
        fahrerListe.setModel(fahrerListModel);
        fahrerListManager = new ListManager(fahrerListe, fahrerListModel);
        ArrayList<String> temp = dbAdapter.getAllFahrerAsStringList();
        fahrerListManager.updateList(temp);
        updateFahrerComboBox(temp);

        DefaultListModel ordersListModel = new DefaultListModel();
        orderListe.setModel(ordersListModel);
        ordersListManager = new ListManager(orderListe, ordersListModel);
        //ordersListManager.updateList(dbAdapter.getOrders());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualOrderLabel;
    private javax.swing.JButton addButt;
    private javax.swing.JComboBox chooseFahrerBox;
    private javax.swing.JButton clearBut;
    private javax.swing.JTextField editFahrerFNameText;
    private javax.swing.JTextField editFahrerLNameText;
    private javax.swing.JButton exitBut;
    private javax.swing.JList fahrerListe;
    private javax.swing.JLabel firstNum;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton orderDoneBut;
    private javax.swing.JComboBox orderGoalXBox;
    private javax.swing.JComboBox orderGoalYBox;
    private javax.swing.JList orderListe;
    private javax.swing.JComboBox orderStartXBox;
    private javax.swing.JComboBox orderStartYBox;
    private javax.swing.JButton retrieveOrder;
    private javax.swing.JLabel secontNum;
    private javax.swing.JButton submitFahrerBut;
    private javax.swing.JButton submitOrderBut;
    // End of variables declaration//GEN-END:variables

}
